### ISSUE TITLE
Add ability to download chapters.

### ISSUE THREAD

**Issue by m-haisham** [nacht-org/nacht#5]
The downloaded content must be stored in the filesystem so that the database would not be bloated.

### Requirements

This list will be updated as work progresses.

- [x] #13
- [x] #6
- [x] https://github.com/nacht-org/nacht_sources/pull/3
- [x] #23

**Comment by mensch272** [comment]
This has been pushed back to version 3 as we are unsure of how we would implement downloads currently.
